server:
  port: 8082
  servlet:
    context-path: /flowable-ui

flowable:
  admin:
    app:
      security:
        encryption:
          credentials-i-v-spec: j8kdO2hejA9lKmm6
          credentials-secret-spec: 9FGl73ngxcOoJvmL
  async-executor-activate: false
  common:
    app:
      idm-admin:
        password: test
        user: admin
      role-prefix: ''
  database-schema-update: true
  form-field-validation-enabled: false
  idm:
    app:
      admin:
        email: test-admin@example-domain.tld
        first-name: Test
        last-name: Administrator
        password: test
        user-id: admin
    enabled: true
  modeler:
    app:
      rest-enabled: true
  rest:
    app:
      admin:
        first-name: Rest
        last-name: Admin
        password: test
        user-id: admin
      authentication-mode: verify-privilege
  task:
    app:
      rest-enabled: true
logging:
  level:
    org:
      flowable: error
management:
  endpoint:
    health:
      roles: access-admin
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  aop:
    auto: false
    proxy-target-class: false
  application:
    name: flowableUI
  banner:
    location: classpath:/org/flowable/spring/boot/flowable-banner.txt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idleTimeout: 300000
      maxLifetime: 600000
      maximumPoolSize: 50
      minimumIdle: 10
      poolName: ${spring.application.name}
    name: defaultDataSource
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/flowable6?nullCatalogMeansCurrent=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
  jmx:
    default-domain: ${spring.application.name}
    unique-names: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  security:
    filter:
      dispatcher-types: REQUEST,FORWARD,ASYNC

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kim.flowable.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn